const fs = require('fs');
const allLines = fs.readFileSync('src/App.tsx', 'utf8').split('\n');

// Extract logo base64 from existing file
const logoLineIdx = allLines.findIndex(l => l.includes("const logoB64 = '"));
const logoLine = allLines[logoLineIdx];
const q1 = logoLine.indexOf("'") + 1;
const q2 = logoLine.lastIndexOf("'");
const logoB64 = logoLine.substring(q1, q2);
console.log('Logo extracted: ' + logoB64.length + ' chars');

// New function body replaces indices 231-510 (1-indexed lines 232-511)
// Uses \r\n for CRLF compatibility
const R = '\r';

const newBody = [
  '    const fmtDate = (d: string | null | undefined) => d ? new Date(d).toLocaleDateString(\'en-ZA\') : \'\'',
  '    const val = (v: any) => v || \'\'',
  '    const logoB64 = \'' + logoB64 + '\'',
  '    const logoHtml = \'<img src="data:image/png;base64,\' + logoB64 + \'" alt="ERHA" style="height:50px">\'',
  '',
  '    const buildPage = async (j: any): Promise<string> => {',
  '      const { data: jItems } = await supabase.from(\'job_line_items\').select(\'*\').eq(\'job_id\', j.id).order(\'sort_order\')',
  '      const items = jItems || []',
  '      const lineItemRows = items.length > 0',
  '        ? items.map((item: any) => \'<tr><td style="border:1px solid #000;padding:3px 5px">\' + (item.description||\'\')+\'</td><td style="border:1px solid #000;padding:3px 5px;text-align:center">\' + (item.quantity||1) + \'</td></tr>\').join(\'\')',
  '        : \'<tr><td style="border:1px solid #000;padding:3px 5px" colspan="2">\u2014</td></tr>\'',
  '      const card = [',
  '        \'<div class="page">\'',
  '        ,\'<table style="margin-bottom:4px"><tr>\'',
  '        ,\'<td style="width:35%">\' + logoHtml + \'</td>\'',
  '        ,\'<td style="width:20%;text-align:center;font-weight:bold;font-size:10pt;vertical-align:middle">Q C<br>Department</td>\'',
  '        ,\'<td style="width:45%;font-size:8pt;border:1px solid #000;padding:4px"><strong>Approved date:</strong> 2022/12/06<br><strong>Revision:</strong> 1<br><strong>Next Revision date:</strong> 2023/12/06<br><strong>Form no:</strong> QCL JC 001</td>\'',
  '        ,\'</tr></table>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px"><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px;width:30%"><strong>Contract Work</strong><br><span style="font-size:8pt;font-style:italic">Panels, Lances, EBT Devices, Taphole Flanges, Ladle</span><div style="margin-top:4px">\' + (j.is_contract_work ? \'&#10003; YES\' : \'&#9633; NO\') + \'</div></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px;width:30%"><strong>Quoted Work</strong><div style="margin-top:4px">\' + (!j.is_contract_work ? \'&#10003; YES\' : \'&#9633; NO\') + \'</div></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px;width:40%"><strong>Compiled by:</strong><br><table><tr><td style="padding-right:12px"><strong>CHERISE</strong> \' + ((j as any).compiled_by===\'Cherise\'?\'&#10003;\':\'\') + \'</td><td><strong>JUANIC</strong> \' + ((j as any).compiled_by===\'Juanic\'?\'&#10003;\':\'\') + \'</td></tr></table></td>\'',
  '        ,\'</tr></table>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px"><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px;width:40%"><strong><u>Employee:</u></strong> <span style="border-bottom:1px solid #000;display:inline-block;min-width:120px">\' + val(j.assigned_employee_name) + \'</span></td>\'',
  '        ,\'<td colspan="4" style="padding:0"><table style="width:100%"><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px"><strong>Job Nr:</strong><br><span style="font-size:10pt;font-weight:900">\' + val(j.job_number) + \'</span></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px"><strong>JOB CARD NO:</strong><br><span style="font-size:10pt;font-weight:900">\' + val(j.job_number) + \'</span></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px"><strong>RFQ:</strong><br>\' + val(j.rfq_no) + \'</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 6px"><strong>SITE REQ:</strong><br>\' + val(j.site_req) + \'</td>\'',
  '        ,\'</tr></table></td></tr></table>\'',
  '        ,\'<div class="section-label">ACTIONS REQUIRED</div>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px">\'',
  '        ,\'<tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:20%">\' + (j.action_manufacture?\'&#10003;\':\'\') + \' <strong>MANUFACTURE</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:20%">\' + (j.action_service?\'&#10003;\':\'\') + \' <strong>SERVICE</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:20%">\' + (j.action_repair?\'&#10003;\':\'\') + \' <strong>REPAIR</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:20%">\' + (j.action_modify?\'&#10003;\':\'\') + \' <strong>MODIFY</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:20%">\' + (j.is_emergency?\'&#9888; EMERGENCY\':\'\') + \'</td>\'',
  '        ,\'</tr><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_sandblast?\'&#10003;\':\'\') + \' <strong>SANDBLAST</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_paint?\'&#10003;\':\'\') + \' <strong>PAINT</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_installation?\'&#10003;\':\'\') + \' <strong>INSTALLATION</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px"></td><td style="border:1px solid #000;padding:3px 8px"></td>\'',
  '        ,\'</tr><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_prepare_material?\'&#10003;\':\'\') + \' <strong>PREPARE MATERIAL</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_other?\'&#10003;\':\'\') + \' <strong>OTHER</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_cut?\'&#10003;\':\'\') + \' <strong>CUT</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">\' + (j.action_machining?\'&#10003;\':\'\') + \' <strong>MACHINING</strong></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px"></td>\'',
  '        ,\'</tr></table>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px">\'',
  '        ,\'<tr><th style="border:1px solid #000;padding:3px 6px;text-align:left;background:#f5f5f5">JOB DESCRIPTION</th><th style="border:1px solid #000;padding:3px 6px;width:60px;text-align:center;background:#f5f5f5"><u>QTY</u></th></tr>\'',
  '        ,lineItemRows',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 6px"><strong>DRAWING:</strong> \' + val(j.drawing_number) + \'</td><td style="border:1px solid #000;padding:3px 6px"></td></tr>\'',
  '        ,\'</table>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px">\'',
  '        ,\'<tr><td colspan="4" style="border:1px solid #000;padding:3px 6px"><strong><u>ATTACHED DOCUMENTS</u></strong></td></tr>\'',
  '        ,\'<tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:25%">&#9633; SERVICE SCHEDULE / QCP</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:25%">&#9633; INFO FOR QUOTE</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:25%">&#9633; DRAWING ATTACHED / SKETCHES</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px;width:25%">&#9633; QCP</td>\'',
  '        ,\'</tr><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">&#9633; INTERNAL ORDER</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px">&#9633; LIST AS QUOTED</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:3px 8px"></td><td style="border:1px solid #000;padding:3px 8px"></td>\'',
  '        ,\'</tr></table>\'',
  '        ,\'<div style="border:1px solid #000;padding:4px 6px;margin-bottom:4px;font-style:italic;font-size:8.5pt"><strong><u>ARTISAN:</u></strong> Make sure you signed the Internal Transmittal to acknowledge the receipt of your job card and the attached documents mentioned above!</div>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px">\'',
  '        ,\'<tr><td colspan="4" style="border:1px solid #000;padding:3px 6px;background:#f5f5f5"><strong><u>SUPERVISOR JOB PLANNING INFO</u></strong></td></tr>\'',
  '        ,\'<tr>\'',
  '        ,\'<th style="border:1px solid #000;padding:3px 6px;width:25%">Date Received</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:3px 6px;width:25%">Material Ordered</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:3px 6px;width:25%">Completion Date<br><span style="font-size:7.5pt;font-weight:normal">(At least 2 days before delivery)</span></th>\'',
  '        ,\'<th style="border:1px solid #000;padding:3px 6px;width:25%">DUE DATE</th>\'',
  '        ,\'</tr><tr>\'',
  '        ,\'<td style="border:1px solid #000;padding:6px">\' + fmtDate(j.date_received) + \'</td>\'',
  '        ,\'<td style="border:1px solid #000;padding:6px"></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:6px"></td>\'',
  '        ,\'<td style="border:1px solid #000;padding:6px;font-weight:bold">\' + fmtDate(j.due_date) + \'</td>\'',
  '        ,\'</tr></table>\'',
  '        ,\'<div style="font-size:8pt;font-style:italic;margin-bottom:6px">(All above is to be completed by the supervisor)</div>\'',
  '        ,\'<div style="margin-bottom:4px">SUPERVISOR SIGNATURE: <span style="display:inline-block;border-bottom:1px solid #000;width:300px;margin-left:8px"></span></div>\'',
  '        ,\'<div style="margin-bottom:8px">EMPLOYEE SIGNATURE: &nbsp;<span style="display:inline-block;border-bottom:1px solid #000;width:308px;margin-left:8px"></span></div>\'',
  '        ,\'<table style="border:1px solid #000;margin-bottom:4px;font-size:8pt"><thead>\'',
  '        ,\'<tr style="background:#f5f5f5">\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px" rowspan="2">DATE</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px" rowspan="2">DESCRIPTION</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">MON</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">TUES</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">WED</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">THUR</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">FRI</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center">SAT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center">SUN</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:2px 4px;text-align:center" colspan="2">TOTAL</th>\'',
  '        ,\'</tr><tr style="background:#f5f5f5">\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'<th style="border:1px solid #000;padding:1px 3px">NT</th><th style="border:1px solid #000;padding:1px 3px">OT</th>\'',
  '        ,\'</tr></thead><tbody>\'',
  '        ,Array(14).fill(\'<tr>\' + Array(16).fill(\'<td style="border:1px solid #000;padding:5px 3px">&nbsp;</td>\').join(\'\') + \'</tr>\').join(\'\')',
  '        ,\'</tbody></table>\'',
  '        ,\'<table style="border:1px solid #000;font-size:8pt">\'',
  '        ,\'<tr><td colspan="5" style="border:1px solid #000;padding:3px 6px;background:#ffe066"><strong>HOLDING POINTS</strong></td></tr>\'',
  '        ,\'<tr style="background:#f5f5f5"><th style="border:1px solid #000;padding:2px 4px;width:5%">No</th><th style="border:1px solid #000;padding:2px 4px;width:55%">Description</th><th style="border:1px solid #000;padding:2px 4px;width:15%">Pass / Fail</th><th style="border:1px solid #000;padding:2px 4px;width:15%">Applicable / Not Applicable</th><th style="border:1px solid #000;padding:2px 4px;width:10%">QC / Supervisor Signature</th></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">1.</td><td style="border:1px solid #000;padding:3px 4px">Mark out all material &amp; check prior to cutting.</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">2.</td><td style="border:1px solid #000;padding:3px 4px">Cut all material, deburr holes, dress and remove all sharp edges</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">3.</td><td style="border:1px solid #000;padding:3px 4px">Assy &amp; inspect prior to welding (Water passes if applicable)</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">4.</td><td style="border:1px solid #000;padding:3px 4px">Do welding complete as per WPS?</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">5.</td><td style="border:1px solid #000;padding:3px 4px">Do a pressure test on water cooled unit if applicable?</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">6.</td><td style="border:1px solid #000;padding:3px 4px">Clean all spatter and ensure NO sharp edges on workpiece</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">7.</td><td style="border:1px solid #000;padding:3px 4px">Do 100% dimensional &amp; visual inspection prior to painting</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">8.</td><td style="border:1px solid #000;padding:3px 4px">Stamp and paint as required</td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td><td style="border:1px solid #000"></td></tr>\'',
  '        ,\'<tr><td style="border:1px solid #000;padding:3px 4px">9.</td><td colspan="4" style="border:1px solid #000;padding:3px 4px">Final Inspection \u2013 Sticker \u2013 Sign \u2013 Paperwork \u2013 Ready for delivery</td></tr>\'',
  '        ,\'<tr><td colspan="5" style="border:1px solid #000;padding:4px 6px;font-size:8pt"><strong>Take Note!!! Final Inspection must ALWAYS be at least 2 days before delivery date!!!!!</strong><br><strong>ALL WELDING RODS MUST BE BAKED PRIOR TO WELDING!!!!!!</strong></td></tr>\'',
  '        ,\'<tr><td colspan="5" style="border:1px solid #000;padding:4px 6px;font-size:8pt;background:#ffe066"><strong>Please follow the above procedure.</strong> See "holding points" \u2014 Under no circumstances should work be continued to the next holding point if the previous holding point is not signed and work completed where applicable.</td></tr>\'',
  '        ,\'</table>\'',
  '        ,\'<div style="margin-top:6px;font-size:7pt;color:#888;display:flex;justify-content:space-between"><span>ERHA Fabrication &amp; Construction \u2014 Confidential</span><span>Printed: \' + new Date().toLocaleString(\'en-ZA\') + \'</span><span>PUSH AI Foundation &copy; 2026</span></div>\'',
  '        ,\'</div>\'',
  '      ].join(\'\')',
  '      return card',
  '    }',
  '',
  '    const pages: string[] = []',
  '    pages.push(await buildPage(job))',
  '    if (job.is_parent) {',
  '      const { data: childJobsData } = await supabase.from(\'jobs\').select(\'*\').eq(\'parent_job_id\', job.id).order(\'job_number\')',
  '      const childJobs = (childJobsData || []) as any[]',
  '      for (const child of childJobs) {',
  '        pages.push(await buildPage(child))',
  '      }',
  '    }',
  '',
  '    const html = \'<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Job Card - \' + val(job.job_number) + \'</title>\'',
  '      + \'<style>* { margin:0; padding:0; box-sizing:border-box; } body { font-family:Arial,sans-serif; font-size:9pt; background:white; color:#000; } .page { width:210mm; min-height:297mm; margin:0 auto; padding:6mm 8mm; } table { border-collapse:collapse; width:100%; } td, th { font-size:9pt; } .print-bar { background:#1e3a5f; color:white; padding:8px 16px; text-align:center; position:sticky; top:0; z-index:100; } .print-btn { background:#4a9a4a; color:white; border:none; padding:6px 20px; font-size:10pt; font-weight:bold; border-radius:4px; cursor:pointer; margin-right:8px; } .section-label { font-weight:bold; font-size:8pt; text-decoration:underline; margin:4px 0 2px; } @media print { .print-bar { display:none } @page { size:A4; margin:8mm } .page { margin:0; padding:6mm 8mm; width:210mm; } table { page-break-inside: auto; border-collapse: collapse; } tr { page-break-inside: avoid; } thead { display: table-header-group; } }</style></head><body>\'',
  '      + \'<div class="print-bar"><button class="print-btn" onclick="window.print()">&#128424; Print Job Card</button><span style="font-size:9pt;opacity:.8">Ctrl+P \u2192 Save as PDF</span></div>\'',
  '      + pages.join(\'<div style="page-break-before:always"></div>\')',
  '      + \'</body></html>\'',
  '    const win = window.open(\'\', \'_blank\')',
  '    if (win) { win.document.write(html); win.document.close() }',
].map(l => l + R);

// Splice: keep lines 0-230 (fn signature at 230), replace 231-510, keep 511+
const before = allLines.slice(0, 231);   // indices 0-230 inclusive
const after  = allLines.slice(511);      // index 511 onwards (closing brace of fn)

const result = [...before, ...newBody, ...after];
fs.writeFileSync('src/App.tsx', result.join('\n'));
console.log('Done - handlePrintJobCard refactored with buildPage helper');
console.log('Parent + all child jobs now print in one window on separate pages');
