const fs = require('fs');
const lines = fs.readFileSync('src/App.tsx', 'utf8').split('\n');

const component = [
  "\r",
  "// WORKSHOP BOARD\r",
  "function WorkshopBoard({ jobs, loading, onRefresh, onStatusChange }: {\r",
  "  jobs: Job[]; loading: boolean; onRefresh: () => void; onStatusChange: (jobId: string, status: string) => void\r",
  "}) {\r",
  "  const [selectedJob, setSelectedJob] = React.useState<Job | null>(null)\r",
  "  const [notes, setNotes] = React.useState<Record<string,string>>({})\r",
  "  const COLS = [\r",
  "    { key: 'NOT_STARTED',   label: 'Not Started',   color: 'bg-gray-500'   },\r",
  "    { key: 'IN_PROGRESS',   label: 'In Progress',   color: 'bg-orange-500' },\r",
  "    { key: 'ON_HOLD',       label: 'On Hold',       color: 'bg-red-400'    },\r",
  "    { key: 'QUALITY_CHECK', label: 'Quality Check', color: 'bg-purple-500' },\r",
  "    { key: 'COMPLETE',      label: 'Complete',      color: 'bg-teal-500'   },\r",
  "    { key: 'DISPATCHED',    label: 'Dispatched',    color: 'bg-green-600'  },\r",
  "  ]\r",
  "  const nextStatus: Record<string,string> = {\r",
  "    NOT_STARTED:'IN_PROGRESS', IN_PROGRESS:'QUALITY_CHECK',\r",
  "    ON_HOLD:'IN_PROGRESS', QUALITY_CHECK:'COMPLETE', COMPLETE:'DISPATCHED',\r",
  "  }\r",
  "  const nextLabel: Record<string,string> = {\r",
  "    NOT_STARTED:'Start', IN_PROGRESS:'QC Check',\r",
  "    ON_HOLD:'Resume', QUALITY_CHECK:'Complete', COMPLETE:'Dispatch',\r",
  "  }\r",
  "  if (loading) return <div className=\"flex items-center justify-center h-64\"><p className=\"text-gray-400\">Loading workshop jobs...</p></div>\r",
  "  return (\r",
  "    <div className=\"flex gap-4 h-full overflow-x-auto pb-4\">\r",
  "      {COLS.map(col => {\r",
  "        const cards = jobs.filter(j => j.workshop_status === col.key)\r",
  "        return (\r",
  "          <div key={col.key} className=\"flex flex-col min-w-64 w-64 shrink-0\">\r",
  "            <div className={`${col.color} rounded-t-lg px-3 py-2 flex items-center justify-between`}>\r",
  "              <span className=\"text-white text-sm font-bold\">{col.label}</span>\r",
  "              <span className=\"bg-white bg-opacity-25 text-white text-xs font-bold px-2 py-0.5 rounded-full\">{cards.length}</span>\r",
  "            </div>\r",
  "            <div className=\"flex-1 bg-gray-200 rounded-b-lg p-2 min-h-96 space-y-2\">\r",
  "              {cards.length === 0 && <div className=\"flex items-center justify-center h-20\"><p className=\"text-gray-400 text-xs\">No jobs</p></div>}\r",
  "              {cards.map(job => (\r",
  "                <div key={job.id} onClick={() => setSelectedJob(job)}\r",
  "                  className=\"bg-white rounded-lg shadow-sm border-2 border-transparent hover:border-orange-300 p-3 cursor-pointer hover:shadow-md transition-all\">\r",
  "                  <div className=\"flex items-center justify-between gap-1 mb-1\">\r",
  "                    <p className=\"text-xs font-bold text-orange-600\">{job.job_number}</p>\r",
  "                    <span className={`text-xs font-semibold px-1.5 py-0.5 rounded ${job.priority==='URGENT'?'bg-red-100 text-red-700':job.priority==='HIGH'?'bg-orange-100 text-orange-700':'bg-gray-100 text-gray-600'}`}>{job.priority}</span>\r",
  "                  </div>\r",
  "                  <p className=\"text-sm font-medium text-gray-800 line-clamp-2 mb-1\">{job.description||'No description'}</p>\r",
  "                  <p className=\"text-xs text-gray-500 truncate mb-2\">{job.client_name||'-'}</p>\r",
  "                  {job.due_date && <p className=\"text-xs text-red-500 mb-2\">Due: {new Date(job.due_date).toLocaleDateString('en-ZA')}</p>}\r",
  "                  <div className=\"flex gap-1\" onClick={e => e.stopPropagation()}>\r",
  "                    {nextStatus[col.key] && (\r",
  "                      <button onClick={() => onStatusChange(job.id, nextStatus[col.key])}\r",
  "                        className=\"flex-1 py-1 text-xs font-semibold text-white rounded bg-orange-500 hover:bg-orange-600 transition-colors\">\r",
  "                        {nextLabel[col.key]}\r",
  "                      </button>\r",
  "                    )}\r",
  "                    {col.key === 'IN_PROGRESS' && (\r",
  "                      <button onClick={() => onStatusChange(job.id, 'ON_HOLD')}\r",
  "                        className=\"px-2 py-1 text-xs font-semibold text-white rounded bg-red-400 hover:bg-red-500 transition-colors\">\r",
  "                        Hold\r",
  "                      </button>\r",
  "                    )}\r",
  "                  </div>\r",
  "                </div>\r",
  "              ))}\r",
  "            </div>\r",
  "          </div>\r",
  "        )\r",
  "      })}\r",
  "      {selectedJob && (\r",
  "        <div className=\"fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4\">\r",
  "          <div className=\"bg-white rounded-xl shadow-2xl w-full max-w-lg\">\r",
  "            <div className=\"bg-orange-500 text-white px-6 py-4 rounded-t-xl flex items-center justify-between\">\r",
  "              <div>\r",
  "                <h2 className=\"text-lg font-bold\">{selectedJob.job_number}</h2>\r",
  "                <p className=\"text-orange-200 text-xs mt-0.5\">{selectedJob.client_name}</p>\r",
  "              </div>\r",
  "              <button onClick={() => setSelectedJob(null)} className=\"text-orange-200 hover:text-white\"><X size={20} /></button>\r",
  "            </div>\r",
  "            <div className=\"p-6 space-y-4\">\r",
  "              <div className=\"bg-orange-50 border border-orange-200 rounded-lg p-4 grid grid-cols-2 gap-3 text-sm\">\r",
  "                <div><span className=\"text-xs text-gray-500 block\">Status</span><span className=\"font-semibold\">{selectedJob.workshop_status?.replace(/_/g,' ')}</span></div>\r",
  "                <div><span className=\"text-xs text-gray-500 block\">Priority</span><span className=\"font-semibold\">{selectedJob.priority}</span></div>\r",
  "                <div><span className=\"text-xs text-gray-500 block\">Due Date</span><span className=\"font-semibold text-red-600\">{selectedJob.due_date?new Date(selectedJob.due_date).toLocaleDateString('en-ZA'):'-'}</span></div>\r",
  "                <div><span className=\"text-xs text-gray-500 block\">PO Number</span><span className=\"font-semibold\">{(selectedJob as any).po_number||'-'}</span></div>\r",
  "                {selectedJob.time_started_at && <div className=\"col-span-2\"><span className=\"text-xs text-gray-500 block\">Started</span><span className=\"font-semibold\">{new Date(selectedJob.time_started_at).toLocaleString('en-ZA')}</span></div>}\r",
  "              </div>\r",
  "              {selectedJob.description && <div><label className=\"block text-xs font-medium text-gray-500 mb-1\">Description</label><p className=\"text-sm text-gray-800 bg-gray-50 rounded-lg px-3 py-2\">{selectedJob.description}</p></div>}\r",
  "              <div>\r",
  "                <label className=\"block text-xs font-medium text-gray-500 mb-1\">Workshop Notes</label>\r",
  "                <textarea value={notes[selectedJob.id] ?? (selectedJob.workshop_notes||'')} onChange={e => setNotes(n => ({...n,[selectedJob.id]:e.target.value}))} rows={3}\r",
  "                  className=\"w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-orange-400 resize-none\" placeholder=\"Add workshop notes...\" />\r",
  "                <button onClick={async () => { await supabase.from('jobs').update({workshop_notes:notes[selectedJob.id]}).eq('id',selectedJob.id); setSelectedJob(null); onRefresh() }}\r",
  "                  className=\"mt-2 w-full py-2 text-sm font-semibold text-white bg-orange-500 hover:bg-orange-600 rounded-lg transition-colors\">Save Notes</button>\r",
  "              </div>\r",
  "            </div>\r",
  "          </div>\r",
  "        </div>\r",
  "      )}\r",
  "    </div>\r",
  "  )\r",
  "}\r"
];

// Remove existing export default App line and re-add at end
const exportIdx = lines.findIndex(l => l.includes('export default App'));
if (exportIdx > -1) lines.splice(exportIdx, 1);

lines.push(...component);
lines.push("\r");
lines.push("export default App\r");

fs.writeFileSync('src/App.tsx', lines.join('\n'), 'utf8');
console.log('WorkshopBoard component added - ' + component.length + ' lines');
